#!/usr/bin/env bash
#
# script to install or upgrade plex on Ubuntu 64bit
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: September 23, 2015
# License: MIT

pkgdir=~/.plex/pkg
plexurl='https://plex.tv/downloads'

fatal() {
	echo "FATAL: $*" >&2
	exit 1
}

mkdir -p "$pkgdir"

# get the currently installed version
read -r _ installed < <(dpkg-query -W plexmediaserver 2>/dev/null)
echo "installed: ${installed:-(none)}"

# grab the packages
[[ -n $1 ]] && plexurl="https://plex.tv/downloads/latest/1?channel=8&build=linux-ubuntu-x86_64&distro=ubuntu&X-Plex-Token=$1"
html=$(curl -sS $plexurl) || fatal 'failed to list packages'

# find the latest deb
read -r version url < <(perl -lne '/<a href="([^"]+\/plexmediaserver_([^ ]+)_amd64\.deb)"/ && printf "$2 $1\n"' <<< "$html")
[[ -n $version && -n $url ]] || fatal 'failed to extract latest version and download url'
echo "latest: $version"

# exit if we are already at the latest version
if [[ $version == "$installed" ]]; then
	echo 'plex up-to-date'
	exit 0
fi

# install plex
fname="$pkgdir/${url##*/}"
if [[ ! -f $fname ]]; then
	echo "downloading $url to $fname..."
	curl -o "$fname" "$url" || fatal 'failed to download package'
else
	echo "using cached file: $fname"
fi

echo 'installing...'
dpkg -i "$fname" || fatal 'failed to install package'

echo "installed version: $version"
